name: Rust

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        label:
          # - Windows aarch64
          # - Windows i686
          - Windows x86_64
          # - Linux arm Hardware Float
          # - Linux armv7 Hardware Float
          # - Linux aarch64
          # - Linux i686
          - Linux x86_64
          - macOS aarch64
          - macOS x86_64

        include:
          # - label: Windows aarch64
          #   target: aarch64-pc-windows-msvc
          #   os: windows-latest
          #   cross: skip
          #   install_target: true

          # - label: Windows i686
          #   target: i686-pc-windows-msvc
          #   os: windows-latest
          #   cross: skip
          #   install_target: true
          #   bits: 32bit

          - label: Windows x86_64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: skip

          # - label: Linux arm Hardware Float
          #   target: arm-unknown-linux-gnueabihf
          #   os: ubuntu-latest
          #   features: --no-default-features
          #   bits: 32bit

          # - label: Linux armv7 Hardware Float
          #   target: armv7-unknown-linux-gnueabihf
          #   os: ubuntu-latest
          #   features: --no-default-features
          #   bits: 32bit

          # - label: Linux aarch64
          #   target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   features: --no-default-features

          # - label: Linux i686
          #   target: i686-unknown-linux-gnu
          #   os: ubuntu-latest
          #   features: --no-default-features
          #   bits: 32bit

          - label: Linux x86_64
            target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            cross: skip

          - label: macOS aarch64
            target: aarch64-apple-darwin
            os: macOS-latest
            cross: skip

          - label: macOS x86_64
            target: x86_64-apple-darwin
            os: macOS-latest
            cross: skip
            install_target: true

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.toolchain || 'stable' }}

      - name: Install Target
        if: matrix.install_target != ''
        run: rustup target add ${{ matrix.target }}

      - name: Install cross
        if: matrix.cross == ''
        run: sh .github/workflows/install.sh
        env:
          OS_NAME: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}

      - name: Download cross
        if: matrix.cross == '' && matrix.no_std == ''
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "cross-rs/cross"
          latest: true
          fileName: "cross-x86_64-unknown-linux-gnu.tar.gz"
          out-file-path: "/home/runner/.cargo/bin"

      - name: Install cross
        if: matrix.cross == '' && matrix.no_std == ''
        run: |
          cd ~/.cargo/bin
          tar -xzf cross-x86_64-unknown-linux-gnu.tar.gz

      - name: Build
        run: sh .github/workflows/build.sh
        env:
          TARGET: ${{ matrix.target }}
          SKIP_CROSS: ${{ matrix.cross }}
          IS_DEPLOY: ${{ startsWith(github.ref, 'refs/tags/') && (matrix.release_anyway != '' || !(startsWith(matrix.toolchain, 'nightly') || startsWith(matrix.toolchain, 'beta'))) }}
          FEATURES: ${{ matrix.features }}
          OS_NAME: ${{ matrix.os }}

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.release == ''
        shell: bash
        run: .github/workflows/before_deploy.sh
        env:
          OS_NAME: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          PLUGIN_BITS: ${{ matrix.bits || '64bit' }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.release == ''
        uses: softprops/action-gh-release@v1
        with:
          files: asr-debugger-*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
